### ISSUE TITLE
Notification sound URL is down

### ISSUE THREAD

**Issue by uvera** [instantOS/instantNOTIFY#3]
`https://notificationsounds.com/notification-sounds/me-too-603/download/ogg` is not up anymore
![image](https://user-images.githubusercontent.com/5598427/118354066-c3b37680-b558-11eb-997a-adb39fbd13c3.png)

**Comment by paperbenni** [comment]
fixed in https://github.com/instantOS/instantNOTIFY/commit/04fe0053d3e9895504e02a4f555d1bd4b7f79462
